# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: prueba-angel
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ping
      run: |
        sudo ping 127.0.0.1
